import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ThemeProvider } from '@/providers/theme-provider'
import { cn } from '../lib/utils';


const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Discord_Clone',
  description: 'Generated by Manish Tamang',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ClerkProvider >

      <body className={cn(font.className, "bg-white dark:bg-[#313338]")}>
       <ThemeProvider attribute="class"
       storageKey='discord-theme'
       
       enableSystem defaultTheme='system'>
        {children}
       </ThemeProvider>
        </body>
      </ClerkProvider>
    </html>
  )
}
