import { cn } from '@/lib/utils'
import '../globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'


const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Discord_Clone | Auth',
  description: 'Generated by Manish Tamang',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   <div className="min-h-screen flex items-center justify-center">
    {children}
   </div>
    )
}
